src/main/java/com/mitchellbosecke/pebble/utils/OperatorUtils.java
src/test/java/com/mitchellbosecke/pebble/CoreOperatorsTest.java

Issue #46 was occurring since equals comparision of Number objects was done using == which doesn't work in all cases, especially with Float and Double. See http://stackoverflow.com/questions/12226757/
Fixed this by using equals() for eqaulity comaprision of Number objects. Also added a regression test in CoreOperatorsTest.java.
See: https://github.com/mbosecke/pebble/issues/46

issue-46: Fix equals comparision of Number objects to use equals().

---

src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java

We can pass different classes in same template. In this case [invokeMember](https://github.com/mbosecke/pebble/blob/v1.4.4/src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java#L155) will not work

Fix member cache for different types

---

src/main/java/com/mitchellbosecke/pebble/extension/core/CoreExtension.java
src/main/java/com/mitchellbosecke/pebble/extension/core/MapTest.java
src/main/java/com/mitchellbosecke/pebble/extension/core/SliceFilter.java
src/main/java/com/mitchellbosecke/pebble/node/ForNode.java
src/main/java/com/mitchellbosecke/pebble/node/expression/ArrayExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/ContainsExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/MapExpression.java
src/main/java/com/mitchellbosecke/pebble/parser/ExpressionParser.java
src/main/java/com/mitchellbosecke/pebble/utils/OperatorUtils.java
src/test/java/com/mitchellbosecke/pebble/ArraySyntaxTest.java
src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java
src/test/java/com/mitchellbosecke/pebble/CoreOperatorsTest.java
src/test/java/com/mitchellbosecke/pebble/MapSyntaxTest.java

Syntax for instantiating arrays/maps as context variables.
There are a few //FIXME with design decisions that I didn't feel to tackle. Most troubling ones have to do with primitive arrays.
Noteworthy:
- forgot to add tests for MapTest
- forgot to format sources with your style. Sorry!

Array&map support

---

src/main/java/com/mitchellbosecke/pebble/extension/escaper/EscapeFilter.java

This missing break statement means it is impossible to use the escape strategy `url_param`, as it is treated as urecognized. This PR fixes this.

Add missing break statement in EscapeFilter

---

src/main/java/com/mitchellbosecke/pebble/error/RootAttributeNotFoundException.java
src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/ErrorReportingTest.java
src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java
src/test/resources/templates/template.errorReportingMissingRootProperty.peb

I created RootAttributeNotFoundException as a subclasss of AttributeNotFoundException so that it is possible to distinguish the difference if need be. I also changed an existing test that expected NPE, as I feel this is a very generic exception that can hide other issues.

Fix for Pebble issue #76

---

src/main/java/com/mitchellbosecke/pebble/extension/core/CoreExtension.java
src/main/java/com/mitchellbosecke/pebble/extension/core/RsortFilter.java
src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java

Add "rsort" filter to sort list items in the reverse order.
Update: I've noted the comment in the on the ignored test `CoreFiltersTest#testSliceWithPrimitivesArray`. The issue is located in `GetAttributeExpression#evaluate`. The initial implementation handles only array of references, in the second commit I modified it to handle arrays of any type and removed `@Ignore` so now all tests pass.

Add "rsort" filter and fix primitive array subscripting.

---

src/main/java/com/mitchellbosecke/pebble/extension/i18n/UTF8Control.java
src/main/java/com/mitchellbosecke/pebble/extension/i18n/i18nFunction.java
src/test/java/com/mitchellbosecke/pebble/I18nExtensionTest.java
src/test/resources/testMessages_es_US.properties

instead of the default ISO-8859-1 use of UTF-8 should be always the default encoding.

#134 - Load resource bundles using UTF-8 encoding

---

src/main/java/com/mitchellbosecke/pebble/extension/escaper/EscaperNodeVisitor.java
src/main/java/com/mitchellbosecke/pebble/node/ArgumentsNode.java
src/main/java/com/mitchellbosecke/pebble/node/FunctionOrMacroNameNode.java
src/main/java/com/mitchellbosecke/pebble/node/TestInvocationExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/ArrayExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/BinaryExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/BlockFunctionExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/ContextVariableExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/Expression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/FilterExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/FilterInvocationExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/FunctionOrMacroInvocationExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/LiteralBooleanExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/LiteralDoubleExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/LiteralLongExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/LiteralNullExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/LiteralStringExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/MapExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/ParentFunctionExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/PositiveTestExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/RangeExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/RenderableNodeExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/TernaryExpression.java
src/main/java/com/mitchellbosecke/pebble/node/expression/UnaryExpression.java
src/main/java/com/mitchellbosecke/pebble/parser/ExpressionParser.java
src/main/java/com/mitchellbosecke/pebble/tokenParser/FilterTokenParser.java
src/test/java/com/mitchellbosecke/pebble/ArgumentsNodeTest.java

I have add a method for getting the line number on the expression interface.
This helps to pass the line number along the exceptions. One thing which I do not like is the way I had to handle BinaryExpression and UnaryExpression. Since we are using reflections to create new instances we can not pass along the line number in the constructor. Eventually we should apply here the factory pattern. Instead we pass the class name in BinaryOperatorImpl resp. UnaryOperatorImpl we can pass a factory object. This factory object has a method to create new instances of the expressions. We could also pass easily the line number along the factory.
@mbosecke if you like to go the way with the factory I can change this. However the change with the factory would be an even bigger change. I would need to …

Add better error handling within expression

---

src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java

When passing null as an argument, a NullPointerException is thrown. This
PR fixes it

Fix for bean method with Null Arguments 

---

src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java
src/main/java/com/mitchellbosecke/pebble/extension/core/CapitalizeFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/core/DateFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/core/LengthFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/core/LowerFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/core/TitleFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/core/TrimFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/core/UpperFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/core/UrlEncoderFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/escaper/EscapeFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/escaper/EscaperExtension.java
src/main/java/com/mitchellbosecke/pebble/extension/escaper/EscaperNodeVisitor.java
src/main/java/com/mitchellbosecke/pebble/extension/escaper/EscaperNodeVisitorFactory.java
src/main/java/com/mitchellbosecke/pebble/extension/escaper/RawFilter.java
src/main/java/com/mitchellbosecke/pebble/extension/escaper/RawString.java
src/main/java/com/mitchellbosecke/pebble/template/PebbleTemplateImpl.java
src/test/java/com/mitchellbosecke/pebble/EscaperExtensionTest.java

This PR was motivated by our use internally at our company, and realising that functions are not escaped by default. Rather than explicitly making each function escape its output before returning, we thought it would be beneficial for functions to be escaped by default, and require explicit escaping.
To achieve this, the following changes have been made.
* Introduction of test cases to check the escape behaviour of basic functions and macros.
* The introduction of `RawString.java`: a class that the `EscapeFilter` ignores (as it is not a `String`).
* Functions and Macros are not now whitelisted. Instead macros return an instance of `RawString` when evaluated, and functions return whatever they would usually. This means that macros are still never escaped, and functions are by default, but …

Escape functions by default

---

src/main/java/com/mitchellbosecke/pebble/extension/escaper/EscapeFilter.java
src/test/java/com/mitchellbosecke/pebble/EscaperExtensionTest.java

Escape anything, and not just `Strings`.
Previously, the `EscapeFilter` would ignore anything that wasn't a String, this
meant that an object being printed could contain some XSS content in its
`toString()` method (e.g standard java collections that contain a string with
XSS) that didn't get escaped, even if the escape filter was used explicitly.
The `EscapeFilter` now converts anything to a `String` with `toString()`, and then
proceeds as normal.
This PR will conflict with #149 and one or other of them will need to be rebased when the other gets merged, I will of course do this when necessary.
Also worth noting that even if there were no merge conflicts, tests would fail after both were to get merged in as `RawString` would no longer be ignored as required by `EscapeFilter` (so this …

Don't Just escape Strings

---

src/main/java/com/mitchellbosecke/pebble/node/ForNode.java
src/test/java/com/mitchellbosecke/pebble/ArraySyntaxTest.java

Pebble returns a NullPointerException when passing a non-iterable variable (string, number, ..) to a for loop, making hard the task of finding what is that the developer has written wrong in the template.
This PR tries to address that issue, raising a PebbleException and providing information about the error and the line where it occurred.

Throw PebbleException when variable cannot be iterated in a For tag

---

src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java
src/test/resources/templates/template.import.dynamic.macro_ajax.peb
src/test/resources/templates/template.import.dynamic.macro_classic.peb
src/test/resources/templates/template.import.dynamic.peb
src/test/resources/templates/template.include.dynamic.adminFooter.peb
src/test/resources/templates/template.include.dynamic.defaultFooter.peb
src/test/resources/templates/template.include.dynamic.peb

This commit adds tests for the feature that one can use a dynamic expression to determine the template in the include- and import-tag.

Add tests for dynamic include and import

---

src/test/java/com/mitchellbosecke/pebble/LoaderTest.java
src/test/java/com/mitchellbosecke/pebble/TestRelativePath.java

If the path containing the source code has spaces in it, then getResource
returns a URL with spaces replaced by %20, which, when treated as a file
name, fails to find anything.
The solution is to convert to a File object (via URI) as that process
takes care of decoding the %20 (and any other URL encoding that might
creep in).

Fix tests when run from a path containing spaces

---

src/main/java/com/mitchellbosecke/pebble/node/SetNode.java
src/main/java/com/mitchellbosecke/pebble/template/ScopeChain.java
src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java
src/test/java/com/mitchellbosecke/pebble/ScopeChainTest.java

This fixes a problem when using the set tag in a nested for tag. The for
tag pushes a new scope if there is already a "loop" variable in scope. If
a set tag executes in that nested scope, the changes are undone at the end
of the for tag, which is not what users expect.
Example:
{% set x = 1 %}
{% for i in 1..1 %}
{% for j in 1..1 %}
{% set x = 2 %}
{% endfor %}
{% endfor %}
{{ x }}
Previously this would yield "1"; now it will yield "2".

Allow the set tag to update existing values in parent scopes

---

src/main/java/com/mitchellbosecke/pebble/template/ScopeChain.java
src/test/java/com/mitchellbosecke/pebble/ScopeChainTest.java

A local scope should stop the lookup from proceeding along the chain. This
was working in all cases except when the very first scope in the chain was
local.

Stop ScopeChain lookups when first scope is local

---

src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java
src/main/java/com/mitchellbosecke/pebble/lexer/Syntax.java
src/test/java/com/mitchellbosecke/pebble/NewlineTrimmingTest.java

Adds the possibility to use ".enableNewLineTrimming(false)" when  building a PebbleEngine instance so the first newline following a Pebble tag is not trimmed. Trimming the first newline stays the default behavior.

Issue #125 - Disable trimming of the first newline after a tag.

---

pom.xml
src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java
src/main/java/com/mitchellbosecke/pebble/error/RuntimePebbleException.java
src/main/java/com/mitchellbosecke/pebble/node/CacheNode.java
src/main/java/com/mitchellbosecke/pebble/template/EvaluationContext.java
src/test/java/com/mitchellbosecke/pebble/ArraySyntaxTest.java
src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java
src/test/java/com/mitchellbosecke/pebble/ErrorReportingTest.java
src/test/java/com/mitchellbosecke/pebble/MapSyntaxTest.java
src/test/java/com/mitchellbosecke/pebble/ParsingOdditiesTest.java
src/test/java/com/mitchellbosecke/pebble/TernaryExpressionTest.java

I made the replacement of the cache, updated some dependencies' version and fixed the involved unit tests.
Instead of creating a cache with max size set to zero, I decided to set the cache to `null`. I believe it should be faster to not pass through the cache, since it would always creates a `CompletableFuture` to compute the value that we have to return.

Replacing Guava cache with the one from Caffeine

---

src/main/java/com/mitchellbosecke/pebble/extension/core/DateFilter.java
src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java

added LocalDate, LocalTime, LocalDateTime and ZonedDateTime support for date filter. added fallback to ISO_DATE_TIME pattern, if no pattern was defined. an exception will be thrown, if the pattern can not applied to date object. example LocalTime object with a time pattern.

implemented Java8 Date API support on date filter

---

src/main/java/com/mitchellbosecke/pebble/extension/DynamicAttributeProvider.java
src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java

This is a feature I suggest and that would be really useful for me. It consists in a `DynamicAttributeProvider` interface which, when implemented by an object, tells the expression parser that this object is able to provide attributes _dynamically_, given their names and the potential arguments.
For example :
public class MyObject implements DynamicAttributeProvider {
@Override
public boolean canProvideDynamicAttribute(Object attributeName) {
if("firstname".equals(attributeName)) {
return true;
}
return false;
}
@Override
public Object getDynamicAttribute(Object attributeName, Object[] argumentValues) {
if("firstname".equals(attributeName)) {
return "John";
}
return null;
}
public String getSurname() {
return "Doe";
}
}
Then `"{{ object.firstname }} {{ object.surname }}"` => **John Doe** …

DynamicAttributeProvider

---

CHANGELOG.md
src/main/java/com/mitchellbosecke/pebble/template/PebbleTemplate.java
src/main/java/com/mitchellbosecke/pebble/template/PebbleTemplateImpl.java
src/test/java/com/mitchellbosecke/pebble/RenderSingleBlockTest.java
src/test/resources/templates/single-block/template.renderextendedblock1.peb
src/test/resources/templates/single-block/template.renderextendedblock2.peb

I have recently adopted Pebble for rendering html views in an enterprise application, and thought it could be useful for emails as well. It seems sensible to describe subject, text and html body in the same template, but this would require rendering them as separate blocks.
This PR extends `PebbleTemplate` and `PebbleTemplateImpl` with a new `evaluateBlock()` method that allows rendering of single blocks, similar to the Twig [renderBlock()](https://twig.sensiolabs.org/doc/2.x/api.html#rendering-templates) method.
Happy to improve this if I have missed an easier way!

Extend PebbleTemplate to allow rendering of single blocks

---

src/main/java/com/mitchellbosecke/pebble/extension/core/JoinFilter.java
src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java

JoinFilter is now able to join all all objects which are Iterable and all Arrays. Since Array is not an Iterable the implementation handles Object[] and arrays of primite data types specially.
This is useful if a backend class uses Arrays instead of Lists, for example. If JoinFilter did not support Arrays then either a conversion or a custom JoinFilter would be necessary.

Handle all Iterables and Arrays in JoinFilter 

---

src/main/java/com/mitchellbosecke/pebble/node/IncludeNode.java

This format string does not take any arguments, and `templateName` is `null` anyway, so the string can just be used directly.
Also found on lgtm.com

Replace 0 arg String.format with string.

---

src/main/java/com/mitchellbosecke/pebble/extension/core/RangeFunction.java

these variables never take a null value, so there is no need to use a boxed
Long here.
Also found by lgtm.com

use primitive long in RangeFunction

---

src/main/java/com/mitchellbosecke/pebble/extension/ExtensionRegistry.java

The access methods for this property had been commented out, and are unused, but the contents of the map were still being maintained (unnecessarily).
This problem was found on [lgtm.com](https://lgtm.com), and there are a number of other alerts that it's found: https://lgtm.com/projects/g/PebbleTemplates/pebble/alerts/
If you're interested, you can also set up pull request integration for free to catch the introduction of new alerts: https://lgtm.com/projects/g/PebbleTemplates/pebble/ci/
*Full Disclosure: I'm a core developer at lgtm.com, and we actually use pebble for the administration panel for the enterprise version of lgtm.*

remove unused extensions map in ExtensionRegistry

---

src/main/java/com/mitchellbosecke/pebble/extension/escaper/SafeString.java

`SafeString` had `equals()` defined but not `hashCode()`, this violates the contract required for these methods, and as such, would result in undefined behaviour if `SafeString` objects were used in a hashing data structure.
This problem was found on [lgtm.com](https://lgtm.com), and there are a number of other alerts that it's found: https://lgtm.com/projects/g/PebbleTemplates/pebble/alerts/
If you're interested, you can also set up pull request integration for free to catch the introduction of new alerts: https://lgtm.com/projects/g/PebbleTemplates/pebble/ci/
*Full Disclosure: I'm a core developer at lgtm.com, and we actually use pebble for the administration panel for the enterprise version of lgtm.*

Implement SafeString.hashCode()

---

src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java

The recent change to allow map access via primitives introduced an NPE situtation when null was being passed as the map key.  This PR fixes that issue by skipping `Number.class.isAssignableFrom` if the attributeNameValue is null

Fix NPE in GetAttributeExpression

---

src/main/java/com/mitchellbosecke/pebble/template/ScopeChain.java
src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java
src/test/resources/templates/template.includeOverrideVariable1.peb
src/test/resources/templates/template.includeOverrideVariable2.peb

Previously a null value was interpreted as 'not present in this context' and the parent context was queried. If the parent had a non-null value then the wrong value was used in the included template.
This PR provides a test case and the fix.

Handle null values passed to an include statement

---

src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java

Motivation:
#241 introduced `DynamicAttributeProvider`. Type checking in
`GetAttributeExpression` seems to be pretty expensive, so as
`DynamicAttributeProvider` is not commonly used, Maps and Arrays
branches should have higher priority.
Modification:
Move the `DynamicAttributeProvider` branch down.
Result:
+10% throughput

Handle DynamicAttributeProvider with a lower priority than Maps and Arrays, see #293

---

src/main/java/com/mitchellbosecke/pebble/extension/core/CoreExtension.java
src/main/java/com/mitchellbosecke/pebble/extension/core/ReverseFilter.java
src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java

Added "reverse" as a default filter.
This filter reverses the order of a list received in input without applying any sorting algorithm.
example usage:
```html
{% for word in words | reverse %} {{ word }} {% endfor %}
```

Add Reverse as a default filter

---

src/main/java/com/mitchellbosecke/pebble/node/ForNode.java
src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java

Make "_loop.length_" and "_loop.revindex_" be lazy evaluated, getting its value only if exists in 'for' template block.
This implementation is useful when used with Iterable object.
> "For performance reasons, the use of 'loop.length' or 'loop.revindex' in templates with Iterable object could slow down the iteration in 'for' tag."
> (Iterable haven't size() or lenght() methods, so to get its length is necessary to count until the end of 'iterator.next()' )

Make "loop.length" and "loop.revindex" be lazy evaluated

---

CHANGELOG.md
src/main/java/com/mitchellbosecke/pebble/error/ClassAccessException.java
src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java

added restriction so that you can't access class/getClass attribute from an object, e.g.: `"{{ object.class }}"`. By having an access to it you can execute a shell command.

restricting an access to class/getClass attribute

---

src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java

`allowGetClass` flag was always returning null or throwing ClassAccessException, even when it should have been allowed. This PR fixes that bug, and tests that it conforms to the following truth table (with the prior results also shown):
| AllowGetClass | Strict Variables | Access Type | Expected Result | Prior Result |
| ------------- | ---------------- | ----------- | --------------- | ------------ |
| true          | false            | property    | allowed         | null         |
| true          | false            | method      | allowed         | null         |
| true          | true             | property    | allowed         | throw        |
| true          | true             | method      | allowed         | throw        |
| false         | false            | property    | null …

Makes logic with allowGetClass and strictVariables well-defined

---

src/main/java/com/mitchellbosecke/pebble/attributes/ArrayResolver.java
src/main/java/com/mitchellbosecke/pebble/attributes/DefaultAttributeResolver.java
src/main/java/com/mitchellbosecke/pebble/attributes/ListResolver.java
src/main/java/com/mitchellbosecke/pebble/attributes/MacroResolver.java
src/main/java/com/mitchellbosecke/pebble/attributes/MapResolver.java
src/main/java/com/mitchellbosecke/pebble/attributes/ResolvedAttribute.java
src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/ExtendingPebbleTest.java

Motivation:
`ResolvedAttribute` is being introduced in 3.0 and is currently a SAM (could as well be a `Supplier<Object>`, all the more as they are usually implemented as Java lambdas.
The thing is all those lambdas come with a performance penalty, and there's actually not need for functions here. Functions would only be useful if evaluation was lazy, which is not the case.
What is needed here is only a wrapper around the resolved value (we need the wrapper because `AttributeResolver#resolve` can return null, which is different from a null resolved value.
Modification:
Turn ResolvedAttribute into a basic wrapper.
Result:
Better performance

Optimize ResolvedAttribute

---

src/main/java/com/mitchellbosecke/pebble/template/ScopeChain.java

Motivation:
`ScopeChain#get` performs `containsKey` then `get` so it can account for null values.
The current implementation tries to optimize for the single scope case for the chain scanning with saving an Iterator.
It's possible to go further this way.
Modification:
Optimize for the most common use case where the key is defined and there's a single scope.
Only perform a `get` and only check `contains` if the value is null and there is more than one scope.
Result:
Better performance.

Optimize ScopeChain for basic case with single scope

---

src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java

Motivation:
PebbleEngine#getTemplate in branch 3 leaks file descriptor.
This issue causes test suite to often break.
Modification:
Properly close Reader.
Result:
No more fd leak and test suite runs fine.
I didn't investigate if Pebble 2 was suffereing from the same issue.

PebbleEngine#getTemplate leaks file descriptor

---

src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java
src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java

Fix bug causing leaf attribute not to be validated when using maps and strict variables set to true. Previously, for a structure like _person.name.first_ validation would have been performed for _person_ and _name_ but not for _first_.

Validate leaf attribute when using maps

---

src/main/java/com/mitchellbosecke/pebble/extension/writer/PooledSpecializedStringWriter.java
src/main/java/com/mitchellbosecke/pebble/extension/writer/SpecializedWriter.java
src/main/java/com/mitchellbosecke/pebble/extension/writer/StringWriterSpecializedAdapter.java
src/main/java/com/mitchellbosecke/pebble/node/PrintNode.java

Motivation:
* `Writer` is the central output abstraction in Pebble. Sadly, it's intended for Strings and chars so numbers have to be turned into their String representation, which cause excessive allocation for number heavy use cases.
* `StringWriter` doesn't provide any optimization for writing numbers, even though the underlying `StringBuffer` does.
* Java's standard `Writer` implementations are synchronized, which can hurt performance.
Modifications:
* Introduce `SpecializedWriter` that provides a way to optimize for writing numbers
* Provide `StringWriterSpecializedAdapter` that's used internally when user provided a `StringWriter`
* Introduce `PooledSpecializedStringWriter` for reusable in memory `StringWriter`s
Result:
Better performance

Introduce SpecializedWriter, close #351

---

pebble-spring/pebble-spring-boot-2-starter/pom.xml
pebble-spring/pebble-spring-boot-starter/pom.xml
pebble-spring/pebble-spring3/pom.xml
pebble-spring/pebble-spring4/pom.xml
pebble-spring/pebble-spring5/pom.xml
pebble/pom.xml
pom.xml

This is a first step towards https://github.com/PebbleTemplates/pebble/issues/391.
The primary goal for module names should be uniqueness, since they all share a namespace.
The [official naming strategy recommendation](http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-May/000687.html) says:
> Strongly recommend that all modules be named according to the reverse
Internet domain-name convention.  A module's name should correspond
to the name of its principal exported API package, which should also
follow that convention.  If a module does not have such a package, or
if for legacy reasons it must have a name that does not correspond to
one of its exported packages, then its name should at least start
with the reversed form of an Internet domain with which the author is …

Add automatic module names

---

docs/pom.xml
docs/src/orchid/resources/config.yml

Offline PDF can be viewed locally by running ` mvn orchid:serve -P doc` in `docs/` directory and then visiting http://localhost:8080/wiki/book.pdf. I also added a link to the offline docs in the main site menu.

Updates Orchid version, generates offline documentation from Wiki pages

---

pebble/src/main/java/com/mitchellbosecke/pebble/attributes/MapResolver.java
pebble/src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java

Null value in a Map should not throw AttributeNotFoundException, even with StrictVariables on. (#446)

Null value in a Map should not throw AttributeNotFoundException

---

pebble/src/main/java/com/mitchellbosecke/pebble/lexer/LexerImpl.java

In my opinion, the 'state' variable in LexerImpl seems unnecessary. You can remove them by using Stack data structure to check the current state. (Replaced LinkedList to Stack to make it clear that the 'states' is managed by Stack)
All the test cases have passed.

Remove unnecessary variable 'state' in LexerImpl by using Stack

---

pebble/src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java
pebble/src/main/java/com/mitchellbosecke/pebble/extension/ExtensionRegistry.java
pebble/src/test/java/com/mitchellbosecke/pebble/OverrideCoreExtensionTest.java

Resolves #455.
Added `allowOverrideCoreOperators` flag to `PebbleEngine.Builder`. It defaults to `false` to preserve backwards compatibility.
Example usage:
```java
PebbleEngine pebble = new PebbleEngine.Builder()
.loader(new StringLoader())
.extension(new TestExtension())
.allowOverrideCoreOperators(true)
.build();
```
If enabled, it will apply **all** operators defined in provided extension class.
Otherwise it will only apply those operators that are **not already defined** in `CoreExtension.class` operators.

Allow override core operators

---

docs/pom.xml

The issue deploying to GithubPages is fixed in the latest version of Orchid. 
I reproduced the authentication error on 0.17.1, and after updating to 0.17.4 I was able to successfully deploy to my fork. I tested it with the Github token set as both an environment variable and as a Maven CLI property, both successful.

Fix issue deploying Orchid docs

---

pebble/src/main/java/com/mitchellbosecke/pebble/template/PebbleTemplateImpl.java
pebble/src/test/java/com/mitchellbosecke/pebble/EmbedCachingTagTest.java
pebble/src/test/resources/templates/embed/cache/template.base.peb
pebble/src/test/resources/templates/embed/cache/template1.peb
pebble/src/test/resources/templates/embed/cache/template2.peb

Fix issue of embed tag changing cached templates and breaking includes using the same-named template from the cache.
For example, let's say `templateA.peb` embeds `templateX.peb`, while `templateB.peb` just includes it. If template caching is enabled, both the embed and include tag will use the same cached `PebbleTemplateImpl` object. But for the embed tag to work, it needed to change some of the data in that template, so that later on, when it's just included later, the modified template is being included.
By making a shallow copy of the cached template, the embed tag can make the changes it needs to without affecting what's already in the cache.

Fix issue of embed tag changing cached templates

---

pebble/src/main/java/com/mitchellbosecke/pebble/parser/ExpressionParser.java
pebble/src/test/java/com/mitchellbosecke/pebble/node/expression/StringExpressionParserTest.java

Fixes #481, and adds unit tests for String expression parsing.

Fixes bug which allowed sequential String literals to be parsed correctly

---

pebble/src/main/java/com/mitchellbosecke/pebble/template/Scope.java
pebble/src/test/java/com/mitchellbosecke/pebble/ScopeTest.java

Allow to retrieve all variable names of a Scope

---

docs/src/orchid/resources/wiki/guide/installation.md
pebble/src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java
pebble/src/main/java/com/mitchellbosecke/pebble/node/expression/LiteralBigDecimalExpression.java
pebble/src/main/java/com/mitchellbosecke/pebble/parser/ExpressionParser.java
pebble/src/main/java/com/mitchellbosecke/pebble/parser/ParserOptions.java
pebble/src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java

If a literal is big enough, with current implementation there will be a NumberFormatException thrown during the processing of the Template. There should be an option to treat all number literals as BigDecimals. It will help avoiding this exception and also enforce precise arithmetics when performing calculations.

Allow treating all number literals as BigDecimals to avoid NumberFormatExceptions

---

pebble/src/main/java/com/mitchellbosecke/pebble/extension/core/CoreExtension.java
pebble/src/main/java/com/mitchellbosecke/pebble/operator/BinaryOperator.java
pebble/src/main/java/com/mitchellbosecke/pebble/operator/BinaryOperatorImpl.java
pebble/src/main/java/com/mitchellbosecke/pebble/operator/BinaryOperatorType.java
pebble/src/main/java/com/mitchellbosecke/pebble/parser/ExpressionParser.java

Allow completely control the instantiation of the binary expression class

Custom operator can use external context !

---

docs/src/orchid/resources/wiki/filter/date.md
pebble/src/main/java/com/mitchellbosecke/pebble/extension/core/DateFilter.java
pebble/src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java

Fixes #527 
Also reworded the `date` docs a little.
Also fixed a couple of cases that did not used to work (e.g. trying to format an instant with a format that needed time zone info).

Add timeZone parameter to date filter

---

docs/src/orchid/resources/wiki/guide/extending-pebble.md

Hi,
It looks like the docs for custom tags may be outdated? I can't find AbstractTokenParser in the code?
This PR updates the docs in line with the latest SetTokenParser code.

Fix custom tag example

---

pebble/src/main/java/com/mitchellbosecke/pebble/lexer/LexerImpl.java
pebble/src/test/java/com/mitchellbosecke/pebble/lexer/LexerImplTest.java

Resolves #518 
Regex checking if operator is part of variable name looks only for letters whereas variable name can also have digits and underscore.
Example of valid variable names that were failing:
- is_active
- is0

Fix variable name starting with operator

---

docs/src/orchid/resources/wiki/guide/installation.md
pebble/pom.xml
pebble/src/main/java/com/mitchellbosecke/pebble/loader/AbstractServletLoader.java
pebble/src/main/java/com/mitchellbosecke/pebble/loader/Servlet5Loader.java

This PR adds support for Servlet 5.0, which will be part of Jakarta EE 9 (the successor of Java EE), which will be released in about 2 weeks.
The PR contains the following changes.
* Most of the existing code from `ServletLoader` has be moved to `AbstractServletLoader`.
* A new loader named `Servlet5Loader` has been added. The code is essentially the same as in `ServletLoader`.
What do you think?

Added Servlet5Loader to support Servlet 5.0 (fixes #548)

---

pebble/src/main/java/com/mitchellbosecke/pebble/node/ForNode.java

I have disabled accessing map entries as fields in my attribute resolver, so using for loop variables does not work.
I see no reason to not use a special class instead of a map. Probably has a tiny bit better performance as well and it is type-safe.

Special for loop variables class, to support all attribute resolvers

---

pebble/src/main/java/com/mitchellbosecke/pebble/lexer/LexerImpl.java
pebble/src/test/java/com/mitchellbosecke/pebble/lexer/IdentifierTest.java

Fixes #545.
This is needed to call methods or use fields that are not a-z characters, for example éêȩ etc.
These are supported in Java and because Java provides useful patterns for matching starts and parts of identifiers it's better to just use them.
This issue is really important as it prevents completely valid code from running.

Support all Java identifiers

---

docs/src/orchid/resources/wiki/guide/customize-defaults.md
docs/src/orchid/resources/wiki/summary.md
pebble/src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java
pebble/src/main/java/com/mitchellbosecke/pebble/extension/ExtensionCustomizer.java
pebble/src/main/java/com/mitchellbosecke/pebble/extension/ExtensionRegistryFactory.java
pebble/src/test/java/com/mitchellbosecke/pebble/extension/ExtensionCustomizerTest.java
pebble/src/test/java/com/mitchellbosecke/pebble/extension/ExtensionFactoryTest.java

This is a draft for #520 to allow for a customization of the default extensions.
- refactored out the extension loading code from the `PebbleEngine.Builder` into the `ExtensionRegistryFactory` 
- provide a `ExtensionCustomizer` which basically allows to access extensions before loading

issue #520: provide option to customize stock extensions

---

pebble/src/main/java/com/mitchellbosecke/pebble/node/MacroNode.java
pebble/src/test/java/com/mitchellbosecke/pebble/macro/MacroGlobalVariablesTest.java

Fixes #500
This change allows macros to use extension global variables (getGlobalVariables).

Extension global variables in macros

---

docs/src/orchid/resources/wiki/filter/base64decode.md
docs/src/orchid/resources/wiki/filter/base64encode.md
docs/src/orchid/resources/wiki/filter/sha256.md
docs/src/orchid/resources/wiki/summary.md
pebble/src/main/java/com/mitchellbosecke/pebble/extension/core/Base64DecoderFilter.java
pebble/src/main/java/com/mitchellbosecke/pebble/extension/core/Base64EncoderFilter.java
pebble/src/main/java/com/mitchellbosecke/pebble/extension/core/CoreExtension.java
pebble/src/main/java/com/mitchellbosecke/pebble/extension/core/Sha256Filter.java
pebble/src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java

Adding new filters.
Fixes issues  #573 and #572.

New base64encode and sha256 filters

---

pebble/src/main/java/com/mitchellbosecke/pebble/lexer/LexerImpl.java

Fixes #580
A static initializer check for Android to support older android devices which do not support the standard names.

Fix for older Android versions

---

docs/src/orchid/resources/changelog/v3_2_0.md
docs/src/orchid/resources/wiki/guide/installation.md
pebble/src/main/java/io/pebbletemplates/pebble/loader/MemoryLoader.java
pebble/src/test/java/io/pebbletemplates/pebble/LoaderTest.java

This attempts to solve the issue with StringLoader where inheritance is not supported.  This loader uses a flat hierarchy.
```
MemoryLoader memLoader = new MemoryLoader();
memLoader.addFile("home.html", "{% extends \"layout.html\" %}{% block title %} Home {% endblock %}\r\n"
+ "\r\n"
+ "{% block content %}\r\n"
+ "	<h1> Home </h1>\r\n"
+ "	<p> Welcome to my home page. My name is {{ name }}.</p>\r\n"
+ "{% endblock %}");
memLoader.addFile("layout.html", "<!DOCTYPE html>\r\n"
+ "<html>\r\n"
+ "    <head>\r\n"
+ "        <title>Hello Pebble</title>\r\n"
+ "    </head>\r\n"
+ "    <body>\r\n"
+ "        {% block content %}{% endblock %}\r\n"
+ "    </body>\r\n"
+ "</html>");
PebbleEngine engine = new PebbleEngine.Builder().loader(memLoader).build();
PebbleTemplate compiledTemplate = …
```

added loader that works from memory

---

README.md

http://twig.sensiolabs.org/ has been moved to https://twig.symfony.com/.

Fix Twig link in README.md

---

pebble/src/main/java/io/pebbletemplates/pebble/extension/core/ReplaceFilter.java
pebble/src/test/java/io/pebbletemplates/pebble/CoreFiltersTest.java

There is a check missing before doing toString() on the input.

Fix the null pointer exception on the replace filter

---

pebble/src/main/java/io/pebbletemplates/pebble/attributes/DefaultAttributeResolver.java

When a method throws an exception during {% set %}, for example {% set x = someoptional.get %} (with the optional being empty), a non-detailed exception was thrown - very difficult to debug.

Throw a more detailed exception from DefaultAttributeResolver

---

pebble/pom.xml

This allows to use the pebble jar in an OSGi runtime, like Eclipse, out of the box.
The version ranges for the optional dependencies `com.github.ben-manes.caffeine:caffeine`, `javax.servlet` and `jakarta.servlet` have been widened manually because there are newer versions available than the one this library depends on.
If you are interested in updating any of these dependencies (and especially migrate `javax.servlet:servlet-api` to `javax.servlet:javax.servlet-api` or even `jakarta.servlet:jakarta.servlet-api:4.0.2` (which provides the `javax.servlet` packages) I can provide a separate PR or do it in this one.
The OSGi compliant MANIFEST.MF is only generated for the main `pebble` artifact.
If you think this is also relevant for the spring artifacts I can extend the change, but I would not …

Generate OSGi metadata into pebble jar to make it OSGi compliant

---

pom.xml

Add  flag for parameter name retention in maven compiler plugin.
As of https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#parameter-name-retention, it is recommend to add the flag as `LocalVariableTableParameterNameDiscoverer has been removed in 6.1` to be compatible with Spring Boot 3.2.x version (and Spring Framework 6.1.x version)!

Add  flag for parameter name retention in maven compiler plugin

---

pebble/src/main/java/io/pebbletemplates/pebble/loader/MemoryLoader.java

**Summary**
This Pull Request adds a new method getTemplates() to the MemoryLoader class. The method is designed to return a list of all the existing templates currently loaded in memory.
**Background**
In applications that dynamically generate or update Pebble templates, it is often necessary to get a list of all existing templates. However, the MemoryLoader class lacks a method for obtaining this information, which could lead to inefficiencies and limitations in application development.
**Changes**
Added a new method getTemplates() in MemoryLoader class.
Updated relevant unit tests (if applicable).
**Use Case**
This feature will be useful in scenarios where developers need to:
Debug or log currently loaded templates.
Implement functionality that depends on the list of loaded templates.

Added getTemplates function to MemoryLoader

---

pebble-spring/pebble-spring-boot-starter/src/main/java/io/pebbletemplates/boot/autoconfigure/PebbleReactiveWebConfiguration.java
pebble-spring/pebble-spring-boot-starter/src/main/java/io/pebbletemplates/boot/autoconfigure/PebbleServletWebConfiguration.java
pebble-spring/pebble-spring-boot-starter/src/test/java/io/pebbletemplates/boot/autoconfigure/PebbleAutoConfigurationTest.java

The [documentation](https://github.com/search?q=repo:PebbleTemplates/pebble%20Customizing%20the%20ViewResolver&type=code#L110-L117) states we can provide our own `PebbleViewResolver`.
I'm upgrading from Pebble 3.1.0 to the latest 3.2.2, and my `@Bean` for my custom PebbleViewResolver breaks.
Starting the Spring Boot server (version 3.4.2) fails with:
```
The bean 'pebbleViewResolver', defined in class path resource [io/pebbletemplates/boot/autoconfigure/PebbleServletWebConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/myproject/extension/PebbleConfiguration.class] and overriding is disabled.
```
Pebble 3.1.0 had the correct implementation: `@ConditionalOnMissingBean(name = "pebbleViewResolver")`
Whereas 3.2.2 has …

Fix the ability to provide your own PebbleViewResolver

---

pebble-spring/pebble-spring-boot-starter/src/test/java/io/pebbletemplates/boot/Controllers.java
pebble-spring/pebble-spring-boot-starter/src/test/java/io/pebbletemplates/boot/autoconfigure/ReactiveAppTest.java
pebble-spring/pebble-spring-boot-starter/src/test/resources/templates/session.peb
pebble-spring/pebble-spring6/src/main/java/io/pebbletemplates/spring/reactive/PebbleReactiveView.java

This PR tries to fix the problem described at <https://github.com/PebbleTemplates/pebble/pull/513#discussion_r2002957400>.
I override the method `getModelAttributes` to resolve the async attributes automatically, please refer to [here](https://github.com/spring-projects/spring-framework/blob/a376ef36e42e078138c92d7cde6fde38dd426c04/spring-webflux/src/main/java/org/springframework/web/reactive/result/view/AbstractView.java#L227).
At last, I added a unit test against the session resolution.

Fix the problem of not resolving reactive values in models

---

pebble/src/test/java/io/pebbletemplates/pebble/attributes/methodaccess/MethodsProvider.java

The method `ThreadGroup.allowThreadSuspension`  has been [removed](https://github.com/openjdk/jdk/pull/11373) since JDK 21. But the MethodsProvider tries to parse the missing method and unit tests fail. Please see the error logs below:
```java
java.lang.ExceptionInInitializerError
at io.pebbletemplates.pebble.attributes.methodaccess.BlacklistMethodAccessValidatorTest.provideUnsafeMethod(BlacklistMethodAccessValidatorTest.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
at org.junit.jupiter.params.provider.MethodArgumentsProvider.lambda$provideArguments$1(MethodArgumentsProvide …
```

Fix the problem of unit test failure under JDK 21
