src/main/java/com/mitchellbosecke/pebble/loader/FileLoader.java
I think that the FileLoader class works not correctly.
=> Fix: FileLoader ignores the suffix property.

src/main/java/com/mitchellbosecke/pebble/extension/core/NumberFormatFilter.java, src/test/java/com/mitchellbosecke/pebble/CacheTest.java, src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java, src/test/java/com/mitchellbosecke/pebble/CoreFunctionsTest.java, src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java, src/test/java/com/mitchellbosecke/pebble/InheritanceTest.java, src/test/java/com/mitchellbosecke/pebble/ParsingOdditiesTest.java
some tests were broken on my machine, because of other default locale and number formatting settings. i fixed the issues with this pull requests - all tests are now green on my machine.
=> fixed platfrom dependent issues

src/main/java/com/mitchellbosecke/pebble/extension/i18n/i18nFunction.java, src/test/java/com/mitchellbosecke/pebble/I18nExtensionTest.java, src/test/resources/testMessages.properties, src/test/resources/testMessages_es_US.properties
for example:
{{ i18n1("messages”,”phrase”, /* object or collection */) }}
=> enable parameters for i18n with java.text.MessageFormat

src/main/java/com/mitchellbosecke/pebble/node/expression/LessThanExpression.java, src/test/java/com/mitchellbosecke/pebble/CoreOperatorsTest.java
=> Fix less than evaluating as less than or equal (fixes #96)

src/main/java/com/mitchellbosecke/pebble/node/ForNode.java, src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java
=> Additional loop vars: last,first,revindex

src/main/java/com/mitchellbosecke/pebble/extension/core/CoreExtension.java, src/main/java/com/mitchellbosecke/pebble/extension/core/RangeFunction.java, src/main/java/com/mitchellbosecke/pebble/node/expression/RangeExpression.java, src/test/java/com/mitchellbosecke/pebble/CoreFunctionsTest.java, src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java
I have implemented the range function to iterate over a sequence of number
```javascript
{% for i in range(0, 3) %}
{{ i }},
{% endfor %}
{# outputs 0, 1, 2, 3, #}
```
When increment is given (as the third parameter), it specifies the increment (or decrement):
```javascript
{% for i in range(0, 6, 2) %}
{{ i }},
{% endfor %}
{# outputs 0, 2, 4, 6, #}
```
.. operator is just a shortcut for the range function with an increment of 1
```javascript
{% for i in 0..5 %}
{{i}}
{% endfor %}
{# outputs 012345 #}
```
You can achieve exactly the same thing by iterating over character as well :
```javascript
{% for i in 'a'..'e' %}
{{i}}
{% endfor %}
{# outputs abcde #}
```
=> Iterate over a sequence of numbers

src/main/java/com/mitchellbosecke/pebble/utils/StringLengthComparator.java
=> clean code

src/main/java/com/mitchellbosecke/pebble/extension/core/FirstFilter.java, src/main/java/com/mitchellbosecke/pebble/extension/core/LastFilter.java, src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java
Currently the `first` and `last` filter only support `String` and
`Collection` input, it should support `Object[]`
=> Added 'array' type support for `last` and `first` filter

src/main/java/com/mitchellbosecke/pebble/extension/core/CoreExtension.java, src/main/java/com/mitchellbosecke/pebble/extension/core/ReplaceFilter.java, src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java
Add replace filter as the original twig version implements it (see http://twig.sensiolabs.org/doc/filters/replace.html).
=> Add replace filter

src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java
=> Flag cache active (Issue #146)

src/main/java/com/mitchellbosecke/pebble/parser/ExpressionParser.java, src/test/java/com/mitchellbosecke/pebble/TernaryExpressionTest.java
Just realized that this change may break existing templates :-/
=> Change ternary expression parsing to be more restrictive

src/main/java/com/mitchellbosecke/pebble/extension/escaper/SafeString.java, src/test/java/com/mitchellbosecke/pebble/EscaperExtensionTest.java
=> SafeString equals is wrong

src/main/java/com/mitchellbosecke/pebble/extension/core/CoreExtension.java, src/main/java/com/mitchellbosecke/pebble/extension/core/MergeFilter.java, src/test/java/com/mitchellbosecke/pebble/CoreFiltersTest.java, src/test/java/com/mitchellbosecke/pebble/extension/ArrayToStringFilter.java, src/test/java/com/mitchellbosecke/pebble/extension/ListToStringFilter.java, src/test/java/com/mitchellbosecke/pebble/extension/TestingExtension.java
Basic functionality is in place:
- maps with maps, maps with lists
- lists with lists, lists with maps
- arrays with arrays 
Fixes #164
=> Add filter for merging maps/lists/arrays

src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java, src/main/java/com/mitchellbosecke/pebble/node/expression/LiteralStringExpression.java
* GetAttributeExpression.getAttributeNameExpression
* LiteralStringExpression.getValue
These are useful in certain kinds of NodeVisitor.
=> Add a couple of missing getters

src/main/java/com/mitchellbosecke/pebble/template/PebbleTemplateImpl.java
This is useful in certain NodeVisitors.
=> Add hasBlock method to PebbleTemplateImpl

src/main/java/com/mitchellbosecke/pebble/utils/OperatorUtils.java, src/test/java/com/mitchellbosecke/pebble/CoreOperatorsTest.java
This fix is working for me, however you may have an alternate implementation suggestion.
=> Fixes #217: Fix regression of broken SafeString concatenation

src/main/java/com/mitchellbosecke/pebble/node/ForNode.java, src/test/java/com/mitchellbosecke/pebble/node/ForNodeTest.java
=> fix for Variable scope bug (#250)

src/main/java/com/mitchellbosecke/pebble/lexer/Syntax.java
Made Syntax.Builder return itself: #259
=> Made Syntax.Builder return itself for method chaining

CHANGELOG.md, src/main/java/com/mitchellbosecke/pebble/tokenParser/ForTokenParser.java, src/main/java/com/mitchellbosecke/pebble/tokenParser/IfTokenParser.java, src/test/java/com/mitchellbosecke/pebble/CoreTagsTest.java
[#266](https://github.com/PebbleTemplates/pebble/issues/266)
=> Fix for #266

README.md
Minor issue but it'll help the copy/pasters .
=> Fix maven include documentation

.gitignore, src/main/java/com/mitchellbosecke/pebble/tokenParser/BlockTokenParser.java, src/test/java/com/mitchellbosecke/pebble/RenderWithoutEndBlockTest.java
Error message added "endblock tag should be present with block tag starting line number" , if endblock does not exist with block.
=> fix for issue308

src/main/java/com/mitchellbosecke/pebble/PebbleEngine.java
Motivation:
PebbleEngine currently eager loads a Reader on every getTemplate call, even though the compiled template might end up being already present in the cache.
Modification:
When a cache is present, only create the Reader on cache miss.
Result:
Faster `getTemplate` when compiled template is already in cache.
=> Lazy load Reader

src/main/java/com/mitchellbosecke/pebble/node/ForNode.java, src/main/java/com/mitchellbosecke/pebble/node/fornode/LazyLength.java, src/main/java/com/mitchellbosecke/pebble/node/fornode/LazyRevIndex.java, src/test/java/com/mitchellbosecke/pebble/ForTest.java
=> #362: Bugfix loop.length and loop.revindex not of type Number

pebble/src/main/java/com/mitchellbosecke/pebble/attributes/DefaultAttributeResolver.java, pebble/src/main/java/com/mitchellbosecke/pebble/attributes/MemberCacheUtils.java, pebble/src/test/java/com/mitchellbosecke/pebble/OverloadedMethodTest.java
Searches matching methods for best possible match rather than returning the first one that works. Adds member parameter types to MemberCacheKey so overloaded methods get resolved from cache correctly, fixing issues with ClassCastException.
Run with [PebbleTemplates/pebble-performance-test](https://github.com/PebbleTemplates/pebble-performance-test) on my MacBook Pro, 4-core 2.8 GHz CPU, 16GB memory.
**Current 3.0**
34335.014766 (±1423.690763) ops/s
**Including these changes**
34743.663107 (±533.180988) ops/s
**Total Change**
+1.19% (-62.55%) ops/s
=> Fixes issues resolving overloaded methods. Closes #367.

pebble/src/main/java/com/mitchellbosecke/pebble/node/expression/AndExpression.java, pebble/src/main/java/com/mitchellbosecke/pebble/node/expression/OrExpression.java, pebble/src/test/java/com/mitchellbosecke/pebble/LogicTest.java, pebble/src/test/java/com/mitchellbosecke/pebble/StrictModeTest.java
And: Evaluate right expression only if left expression is true
Or: Evaluate right expression only if left expression is false
=> Adjust AndExpression and OrExpression logic (#398)

pebble/src/main/java/com/mitchellbosecke/pebble/attributes/MemberCacheUtils.java, pebble/src/test/java/com/mitchellbosecke/pebble/GetAttributeTest.java
=> issue #435 make allowGetClass check case insensitive

docs/src/orchid/resources/wiki/guide/extending-pebble.md, docs/src/orchid/resources/wiki/operator/comparisons.md
=> Fixed a few typos in the docs

docs/src/orchid/resources/wiki/tag/macro.md
=> Fix doc example about global context in macros

docs/src/orchid/resources/wiki/tag/if.md
If I'm not mistaken, this should be a pipe operator than dot.
=> [doc] Fix the example for length

pebble/src/main/java/io/pebbletemplates/pebble/node/expression/ArrayExpression.java, pebble/src/main/java/io/pebbletemplates/pebble/node/expression/BlockFunctionExpression.java, pebble/src/main/java/io/pebbletemplates/pebble/node/expression/LiteralBigDecimalExpression.java, pebble/src/main/java/io/pebbletemplates/pebble/node/expression/LiteralBooleanExpression.java, pebble/src/main/java/io/pebbletemplates/pebble/node/expression/LiteralDoubleExpression.java, pebble/src/main/java/io/pebbletemplates/pebble/node/expression/LiteralIntegerExpression.java, pebble/src/main/java/io/pebbletemplates/pebble/node/expression/LiteralLongExpression.java, pebble/src/main/java/io/pebbletemplates/pebble/node/expression/MapExpression.java, pebble/src/main/java/io/pebbletemplates/pebble/node/expression/ParentFunctionExpression.java, pebble/src/main/java/io/pebbletemplates/pebble/node/expression/RenderableNodeExpression.java
Added methods to visit and traverse all expression nodes, in order to use these methods in a custom NodeVisitor.
=> Make expression nodes fully visitable

docs/src/orchid/resources/wiki/guide/customize-defaults.md, pebble/src/main/java/io/pebbletemplates/pebble/extension/core/DisallowExtensionCustomizerBuilder.java, pebble/src/test/java/io/pebbletemplates/pebble/extension/ExtensionCustomizerTest.java
we needs to dynamically open different feature according to different scenarios.
After adding this, most default feature choose can be done through config files without writing code
=> add ConfigurableExtensionCustomizer
